name: Review assigning

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
  pull_request_review:

jobs:
  reviews:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: Generate app token
        id: tokenizer
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.ORG_CI_APP_ID }}
          private_key: ${{ secrets.ORG_CI_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.tokenizer.outputs.token }}

      - name: Get PR ref
        uses: actions/github-script@v5
        id: pr-ref
        with:
          script: |
            const prNum = ${{ toJSON(github.event.pull_request.number) }};
            if(prNum) return prNum;
            for(const { head: { ref }, number } of ${{ toJSON(github.event.workflow_run.pull_requests) }}){
              if(ref === ${{ toJSON(github.event.workflow_run.head_branch) }}){
                return number;
              }
            }
          result-encoding: string

      - name: Set reviewers or merge
        uses: KaMeHb-UA/auto-review-action@v10
        with:
          scheme-file: "${{ github.workspace }}/.github/review-scheme.yml"
          token: ${{ steps.tokenizer.outputs.token }}
          ref: refs/pull/${{ steps.pr-ref.outputs.result }}/merge
          type: distributed
